In [1]:
import tensorflow as tf

a = tf.constant(100)
b = tf.constant(50)

add_operation = a + b

v = tf.Variable(0)

assign_operation = tf.assign(v, add_operation)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
sess.run(assign_operation)

print(sess.run(v))

150


In [2]:
a = tf.placeholder(tf.int32, [3])
b = tf.constant(2)

multiply_operation = a * b

sess = tf.Session()

result = sess.run(multiply_operation, feed_dict={a: [1, 2, 3]})
print(result)

result = sess.run(multiply_operation, feed_dict={a: [10, 20, 30]})
print(result)

[2 4 6]
[20 40 60]


In [3]:
a = tf.placeholder(tf.int32, [None])
b = tf.constant(10)

multiply_operation = a * b

sess = tf.Session()

result = sess.run(multiply_operation, feed_dict={a: [1, 2, 3, 4, 5]})
print(result)

result = sess.run(multiply_operation, feed_dict={a: [10, 20]})
print(result)

[10 20 30 40 50]
[100 200]
